# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.2
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
        
      # run tests!
      - run: npm test


  deploy:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: git config --global user.email "satyamyadav3@gmail.com"
      - run: git config --global user.name "Satyam Yadav"   
      - add_ssh_keys:
          fingerprints:
            - "68:94:61:46:bf:03:46:5a:ee:df:72:7d:d7:7d:0a:2a" 
      - run: git submodule update --init      
      - run: npm install
      - run: ./node_modules/hexo/bin/hexo generate && ./node_modules/hexo/bin/hexo deploy
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
